### ISSUE TITLE
`.mapError()` not working?

### ISSUE THREAD

**Issue by pablorecio** [tomlokhorst/Promissum#27]
We are using Promissum in a legacy project that we are trying to upgrade to Swift 3, but I found some issues when doing so.

Say that I have something like:

```
class Api {
  // ... 
  fileprivate func requestJSON(_ path: Path) -> Promise<SuccessResponse<AnyObject>, ApiError> {
    let url = path.url(baseUrl)
    return manager
      .request(url)
      .responseJSONPromise()
      .mapError(self.errorTransformer)
  }
  
  // MARK: Error helpers
  
  fileprivate func errorTransformer(_ error: ErrorResponse) -> ApiError {
    return .networkingError(error.result as NSError)
  }
    
  // ...
}
```

Where `ApiError` is:

```
import Foundation
import Statham

public enum ApiError : Error {
  case notFound
  case networkingError(NSError)
  case jsonDecodingError(Error)
}

extension ApiError: CustomStringConvertible {
  public var description: String {
    switch self {
    case .notFound: return NSLocalizedString("Not Found", comment: "Api Error: resource not found")
    case .networkingError(let error): return error.localizedDescription
    case .jsonDecodingError(let error):
      #if DEBUG
        if let error = error as? JsonDecodeError {
          print(error.fullDescription)
        }
      #endif
      return NSLocalizedString("Server error", comment: "Api Error: Server error")
    }
  }
}
```

The problem comes when using `.mapError()`, where the compiler complains about "Argument passed to call that takes no arguments". Digging in the github, I can see that indeed there is this following method [mapError()](https://github.com/tomlokhorst/Promissum/blob/develop/src/Promissum/Combinators.swift#L177) that does not take any arguments and that is a new addition since the 0.5.0 version.

I can see however the right method [here](https://github.com/tomlokhorst/Promissum/blob/develop/src/Promissum/Promise.swift#L366), but it seems that extension is sort of overriding the right one? Or am I missing something important here?

**Comment by tomlokhorst** [comment]
The swift compiler often shows the "wrong" type of error in case of a type error.

Looking at your code, I'm guessing you're using the [`responseJSONPromise`](https://github.com/tomlokhorst/Promissum/blob/1.0.0/extensions/PromissumExtensions/Alamofire%2BPromise.swift#L125-L127) from the Alamofire extension. That returns a `Promise<SuccessResponse<Any>, ErrorResponse>`, not a `Promise<SuccessResponse<AnyObject>, ErrorResponse>` as you're using here.

**Comment by pablorecio** [comment]
Wow, Xcode does not help sometimes.

Thank you.
