### ISSUE TITLE
Add separate products/targets for Alamofire extensions

### ISSUE THREAD

**Issue by hermanbanken** [tomlokhorst/Promissum#43]
When importing https://github.com/ReactiveX/RxSwift/blob/master/Package.swift as SPM package from Xcode, I got the question which product to add to my project.

Using the same setup  as RxSwift we might be able to include the Alamofire dependency ONLY for that extension product.

**Comment by tomlokhorst** [comment]
Good idea! I've implemented this in https://github.com/tomlokhorst/Promissum/pull/44
